### ISSUE TITLE
Truncation of table/index names

### ISSUE THREAD

**Issue by jwg2s** [scottwoodall/python-pgextras#2]
With the bloat method, I've noticed that index/tables are truncated to what seems like 63 characters. We have many indices that have names longer than this, but use a standard indexing naming pattern (rails).

You can see how this can make the bloat statistics unusable, because there's no way to tell which index on a table is which. Is there a way to skip truncation?

**Comment by scottwoodall** [comment]
Thank you for reporting this issue.  I have this resolved in commit https://github.com/scottwoodall/python-pgextras/commit/1c9f4d3d1307e076c71f273219d08ce4446423ed and have pushed version 0.2.1 to [pypi](https://pypi.org/project/pgextras/).
